# Generated by Django 4.1.4 on 2023-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=20)),
                ('jobtype', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('worktype', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('experience', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20)),
                ('qualification', models.CharField(max_length=20)),
            ],
        ),
    ]
