# Generated by Django 4.1.4 on 2023-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='experience',
            field=models.CharField(choices=[('type', 'type'), ('fulltime', 'fulltime'), ('parttime', 'parttime'), ('work', 'work'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-0', '0-0'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='jobtype',
            field=models.CharField(choices=[('type', 'type'), ('fulltime', 'fulltime'), ('parttime', 'parttime'), ('work', 'work'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-0', '0-0'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='worktype',
            field=models.CharField(choices=[('type', 'type'), ('fulltime', 'fulltime'), ('parttime', 'parttime'), ('work', 'work'), ('hybrid', 'hybrid'), ('remote', 'remote'), ('0-0', '0-0'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20),
        ),
    ]
