# Generated by Django 4.1.4 on 2023-01-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usermodel',
        ),
    ]
