# Generated by Django 4.1.4 on 2023-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='')),
                ('education', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
