# Generated by Django 4.1.4 on 2023-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(upload_to='jobapp/static'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='resume',
            field=models.FileField(upload_to='jobapp/static'),
        ),
    ]
