# Generated by Django 4.1.4 on 2023-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_usermodel_image_alter_usermodel_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('jobtitle', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='jobapp/static')),
            ],
        ),
    ]
