# Generated by Django 4.1.4 on 2023-01-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_userapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapply',
            old_name='jobtitle',
            new_name='job',
        ),
    ]
