# Generated by Django 4.1.4 on 2023-01-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_rename_jobtitle_userapply_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userapply',
            new_name='userapplymodel',
        ),
    ]
